name: 'CI Pipeline'

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          ./gradlew test
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Package
          path: |
            **/build/reports/
            **/build/test-results/
